/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ChainRaceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "currentSeason"
      | "getAttemptsPublic"
      | "getBestTimePublic"
      | "getMyRecord"
      | "getParticipants"
      | "getParticipantsLength"
      | "getRecordOf"
      | "protocolId"
      | "startNewSeason"
      | "submitRaceTime"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "NewSeason" | "RaceSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "currentSeason",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getAttemptsPublic",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBestTimePublic",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyRecord",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipants",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantsLength",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordOf",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startNewSeason",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitRaceTime",
    values: [BytesLike, BytesLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "currentSeason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttemptsPublic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getBestTimePublic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipants",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantsLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "startNewSeason",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitRaceTime",
    data: BytesLike
  ): Result;
}

export namespace NewSeasonEvent {
  export type InputTuple = [newSeasonId: BigNumberish];
  export type OutputTuple = [newSeasonId: bigint];
  export interface OutputObject {
    newSeasonId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RaceSubmittedEvent {
  export type InputTuple = [
    racer: AddressLike,
    timeMs: BigNumberish,
    season: BigNumberish
  ];
  export type OutputTuple = [racer: string, timeMs: bigint, season: bigint];
  export interface OutputObject {
    racer: string;
    timeMs: bigint;
    season: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChainRace extends BaseContract {
  connect(runner?: ContractRunner | null): ChainRace;
  waitForDeployment(): Promise<this>;

  interface: ChainRaceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  currentSeason: TypedContractMethod<[], [bigint], "view">;

  getAttemptsPublic: TypedContractMethod<
    [season: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getBestTimePublic: TypedContractMethod<
    [season: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;

  getMyRecord: TypedContractMethod<
    [season: BigNumberish],
    [
      [string, string, string] & {
        bestTime: string;
        attempts: string;
        hasAny: string;
      }
    ],
    "view"
  >;

  getParticipants: TypedContractMethod<
    [season: BigNumberish, start: BigNumberish, count: BigNumberish],
    [string[]],
    "view"
  >;

  getParticipantsLength: TypedContractMethod<
    [season: BigNumberish],
    [bigint],
    "view"
  >;

  getRecordOf: TypedContractMethod<
    [season: BigNumberish, user: AddressLike],
    [
      [string, string, string] & {
        bestTime: string;
        attempts: string;
        hasAny: string;
      }
    ],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  startNewSeason: TypedContractMethod<[], [void], "nonpayable">;

  submitRaceTime: TypedContractMethod<
    [timeMsE: BytesLike, inputProof: BytesLike, timeMsPlain: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "currentSeason"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAttemptsPublic"
  ): TypedContractMethod<
    [season: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBestTimePublic"
  ): TypedContractMethod<
    [season: BigNumberish, user: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getMyRecord"
  ): TypedContractMethod<
    [season: BigNumberish],
    [
      [string, string, string] & {
        bestTime: string;
        attempts: string;
        hasAny: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParticipants"
  ): TypedContractMethod<
    [season: BigNumberish, start: BigNumberish, count: BigNumberish],
    [string[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParticipantsLength"
  ): TypedContractMethod<[season: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecordOf"
  ): TypedContractMethod<
    [season: BigNumberish, user: AddressLike],
    [
      [string, string, string] & {
        bestTime: string;
        attempts: string;
        hasAny: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "startNewSeason"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitRaceTime"
  ): TypedContractMethod<
    [timeMsE: BytesLike, inputProof: BytesLike, timeMsPlain: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "NewSeason"
  ): TypedContractEvent<
    NewSeasonEvent.InputTuple,
    NewSeasonEvent.OutputTuple,
    NewSeasonEvent.OutputObject
  >;
  getEvent(
    key: "RaceSubmitted"
  ): TypedContractEvent<
    RaceSubmittedEvent.InputTuple,
    RaceSubmittedEvent.OutputTuple,
    RaceSubmittedEvent.OutputObject
  >;

  filters: {
    "NewSeason(uint256)": TypedContractEvent<
      NewSeasonEvent.InputTuple,
      NewSeasonEvent.OutputTuple,
      NewSeasonEvent.OutputObject
    >;
    NewSeason: TypedContractEvent<
      NewSeasonEvent.InputTuple,
      NewSeasonEvent.OutputTuple,
      NewSeasonEvent.OutputObject
    >;

    "RaceSubmitted(address,uint256,uint256)": TypedContractEvent<
      RaceSubmittedEvent.InputTuple,
      RaceSubmittedEvent.OutputTuple,
      RaceSubmittedEvent.OutputObject
    >;
    RaceSubmitted: TypedContractEvent<
      RaceSubmittedEvent.InputTuple,
      RaceSubmittedEvent.OutputTuple,
      RaceSubmittedEvent.OutputObject
    >;
  };
}
